language: node_js

node_js:
  - 16

services:
  - postgresql

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install
  - psql -c "create database ordering_app_test_db;" -U postgres

script:
  - yarn test

notification:
  - email: false