language: node_js

node_js:
  - 16

services:
  - postgresql

install:
  - yarn install

before_script:
  - psql -c "create database ordering_app_test_db;" -U postgres

script:
  - yarn test

notification:
  - email: false